#!/bin/bash

echo $1 $2 $#
if ! [ $1 = "file" ] && ! [ $1 = "dir " ] && ! [ $# -eq 2 ]
then
	echo NO
	exit 1
else
	if [ $1 = "file" ]
	then
		echo find $( ls | find . -type f -perm u+r )
		temp=$( ls | grep $2 | grep "^-" )
		echo here $temp
	else
		if [ -d $2 ] && [ -r $2 ]
		then
			echo YES
			exit 0
		fi
	fi
fi
