#!/bin/bash

total=0
while read x y
do
	if [ -z $( echo $x | grep "+\|-" ) ] && [ -z $( echo $y | grep "^[0-9]*$" ) ]
	then
		echo Invald Input
	elif ! [ -z $( echo $x | grep "+" ) ]
	then
		total=$(expr $total \+ $y)
	else
		total=$(expr $total \- $y)
	fi
done
echo Result: $total >/dev/stdout
